<?php

return [
    'module' => [
        'slug' => 'pilot-project-keluarga-sehat',
        'label' => 'Laporan Pelaksanaan Pilot Project Gerakan Keluarga Sehat Tanggap dan Tangguh Bencana',
        'pages' => '202-211',
        'default_period' => [
            'tahun_awal' => 2021,
            'tahun_akhir' => 2024,
        ],
    ],

    // Catalog indikator diselaraskan dengan pedoman halaman 202-211 (Lampiran 3 Pilot Project Pokja IV).
    'sections' => [
        [
            'code' => 'DATA_DUKUNG',
            'label' => 'A. Data Dukung',
            'storage_section' => 'data_dukung',
            'clusters' => [
                [
                    'code' => 'SUPPORT',
                    'label' => 'Indikator Umum',
                    'indicators' => [
                        ['code' => 'jumlah_penduduk', 'label' => 'Jumlah penduduk'],
                        ['code' => 'jumlah_keluarga', 'label' => 'Jumlah keluarga'],
                        ['code' => 'jumlah_laki_laki', 'label' => 'Jumlah laki-laki'],
                        ['code' => 'jumlah_perempuan', 'label' => 'Jumlah perempuan'],
                        ['code' => 'jumlah_keluarga_sejahtera', 'label' => 'Jumlah Keluarga Sejahtera'],
                        ['code' => 'jumlah_keluarga_pra_sejahtera', 'label' => 'Jumlah Keluarga Pra Sejahtera'],
                        ['code' => 'jumlah_rumah', 'label' => 'Jumlah Rumah'],
                        ['code' => 'jumlah_bayi_0_2_tahun', 'label' => 'Jumlah Bayi (0-2 Tahun)'],
                        ['code' => 'jumlah_bayi_asi_eksklusif_0_6_bulan', 'label' => 'Jumlah Bayi yang mendapatkan ASI Eksklusif (0-6 Bulan)'],
                        ['code' => 'jumlah_balita_2_5_tahun', 'label' => 'Jumlah Balita (>2-5 Tahun)'],
                        ['code' => 'jumlah_anak_6_14_tahun', 'label' => 'Jumlah Anak (6-14 Tahun)'],
                        ['code' => 'jumlah_usia_produktif_15_64_tahun', 'label' => 'Jumlah Usia Produktif (15-64 Tahun)'],
                        ['code' => 'jumlah_lansia_65_tahun', 'label' => 'Jumlah Lansia (>=65 Tahun)'],
                        ['code' => 'jumlah_pasangan_usia_subur', 'label' => 'Jumlah Pasangan Usia Subur'],
                        ['code' => 'jumlah_peserta_kb_aktif', 'label' => 'Jumlah Peserta KB Aktif'],
                        ['code' => 'jumlah_ibu_hamil', 'label' => 'Jumlah Ibu Hamil'],
                        ['code' => 'jumlah_ibu_menyusui', 'label' => 'Jumlah Ibu Menyusui'],
                        ['code' => 'jumlah_kelompok_pkk_rt_rw', 'label' => 'Jumlah Kelompok PKK RT/RW'],
                        ['code' => 'jumlah_kader_pkk_pokja_iv', 'label' => 'Jumlah Kader PKK Pokja IV'],
                        ['code' => 'jumlah_kader_pkk_terlatih', 'label' => 'Jumlah Kader PKK Terlatih'],
                        ['code' => 'jumlah_kelompok_dasawisma', 'label' => 'Jumlah Kelompok Dasa Wisma'],
                        ['code' => 'jumlah_kader_dasawisma', 'label' => 'Jumlah Kader Dasa Wisma'],
                        ['code' => 'jumlah_kader_dasawisma_terlatih', 'label' => 'Jumlah Kader Dasa Wisma Terlatih'],
                        ['code' => 'jumlah_bank_sampah', 'label' => 'Jumlah bank sampah'],
                        ['code' => 'jumlah_posko_bencana', 'label' => 'Jumlah posko bencana'],
                    ],
                ],
            ],
        ],
        [
            'code' => 'DATA_PILOT_PROJECT',
            'label' => 'B. Data Pilot Project',
            'storage_section' => 'pilot_project',
            'clusters' => [
                [
                    'code' => 'I',
                    'label' => 'Pilot Project Keluarga Sehat Tanggap dan Tangguh Bencana Peduli Stunting',
                    'indicators' => [
                        ['code' => 'jumlah_bayi_lahir_prematur', 'label' => 'Jumlah Bayi Lahir Prematur'],
                        ['code' => 'jumlah_bayi_lahir_bblr', 'label' => 'Jumlah Bayi Lahir Berat Badan Bayi Lahir Rendah (BBLR)'],
                        ['code' => 'jumlah_balita_kurang_gizi', 'label' => 'Jumlah Balita Kurang Gizi'],
                        ['code' => 'jumlah_balita_stunting', 'label' => 'Jumlah Balita Stunting'],
                        ['code' => 'jumlah_bayi_balita_pemeriksaan_tumbuh_kembang', 'label' => 'Jumlah bayi dan balita yang rutin dilakukan pemeriksaan tumbuh kembang setiap bulan'],
                        ['code' => 'jumlah_kehamilan_tidak_direncanakan', 'label' => 'Jumlah kehamilan yang tidak direncanakan / tidak diinginkan'],
                        ['code' => 'jumlah_ibu_melahirkan_jarak_terlalu_dekat', 'label' => 'Jumlah Ibu yang melahirkan dengan jarak terlalu dekat'],
                    ],
                ],
                [
                    'code' => 'II',
                    'label' => 'Pilot Project Keluarga Sehat Tanggap dan Tangguh Bencana Menuju Perilaku Hidup Bersih dan Sehat (PHBS)',
                    'indicators' => [
                        ['code' => 'jumlah_penduduk_mematuhi_protokol_kesehatan', 'label' => 'Jumlah penduduk yang mematuhi protokol kesehatan'],
                        ['code' => 'jumlah_rumah_memiliki_jamban_sehat', 'label' => 'Jumlah rumah yang memiliki jamban sehat'],
                        ['code' => 'jumlah_rumah_memiliki_instalasi_air_bersih', 'label' => 'Jumlah rumah yang memiliki fasilitas instalasi atau bak penampung air bersih'],
                        ['code' => 'jumlah_kasus_diare', 'label' => 'Jumlah kasus penyakit Diare'],
                        ['code' => 'jumlah_keluarga_sadar_gizi', 'label' => 'Jumlah keluarga yang sadar gizi'],
                        ['code' => 'jumlah_rumah_tanpa_asap_rokok', 'label' => 'Jumlah rumah tanpa asap rokok'],
                        ['code' => 'jumlah_penduduk_babs', 'label' => 'Jumlah penduduk yang masih Buang Air Besar Sembarangan (BABS)'],
                    ],
                ],
                [
                    'code' => 'III',
                    'label' => 'Pilot Project Keluarga Sehat Tanggap dan Tangguh Bencana Peduli Kesehatan Ibu dan Anak (KIA)',
                    'indicators' => [
                        ['code' => 'jumlah_ibu_hamil_periksa_periodik', 'label' => 'Jumlah ibu hamil yang rutin memeriksakan kehamilannya pada tenaga kesehatan secara periodik'],
                        ['code' => 'jumlah_persalinan_ditolong_nakes', 'label' => 'Jumlah Persalinan yang ditolong Tenaga Kesehatan'],
                        ['code' => 'jumlah_kasus_kematian_ibu_nifas', 'label' => 'Jumlah kasus Kematian Ibu nifas'],
                        ['code' => 'jumlah_kasus_kanker_serviks_perempuan', 'label' => 'Jumlah kasus Kanker Serviks pada Perempuan'],
                        ['code' => 'jumlah_bayi_balita_imunisasi', 'label' => 'Jumlah bayi dan balita yang mendapat imunisasi'],
                        ['code' => 'jumlah_bayi_balita_sakit_terdata_faskes', 'label' => 'Jumlah bayi dan balita sakit yang terdata pada fasilitas kesehatan'],
                        ['code' => 'jumlah_kasus_kematian_bayi_balita', 'label' => 'Jumlah kasus Kematian Bayi dan Balita'],
                    ],
                ],
                [
                    'code' => 'IV',
                    'label' => 'Pilot Project Keluarga Sehat Tanggap dan Tangguh Bencana Siaga Kebakaran Lingkungan',
                    'indicators' => [
                        ['code' => 'jumlah_kasus_kebakaran_rumah_tangga', 'label' => 'Jumlah kasus Kebakaran Rumah Tangga'],
                        ['code' => 'jumlah_kasus_kebakaran_non_rumah_tangga', 'label' => 'Jumlah kasus kebakaran non rumah tangga'],
                        ['code' => 'jumlah_rumah_tangga_memiliki_apar', 'label' => 'Jumlah Rumah Tangga yang memiliki Alat Pemadam Api Ringan (APAR) atau Instalasi Air untuk antisipasi kebakaran'],
                        ['code' => 'jumlah_rumah_semi_permanen_dan_rumah_kayu', 'label' => 'Jumlah Rumah Semi Permanen dan rumah kayu'],
                        ['code' => 'jumlah_rumah_tangga_memiliki_kotak_p3k', 'label' => 'Jumlah Rumah Tangga yang memiliki Kotak P3K'],
                        ['code' => 'jumlah_kasus_kecelakaan_rumah_tangga', 'label' => 'Jumlah kasus Kecelakaan Rumah Tangga'],
                        ['code' => 'jumlah_instalasi_hydrant_antisipasi_kebakaran', 'label' => 'Jumlah instalasi hydrant antisipasi kebakaran'],
                    ],
                ],
                [
                    'code' => 'V',
                    'label' => 'Pilot Project Keluarga Sehat Tanggap dan Tangguh Bencana Alam',
                    'indicators' => [
                        ['code' => 'jumlah_kasus_bencana_alam', 'label' => 'Jumlah kasus Bencana Alam'],
                        ['code' => 'jumlah_kasus_kerusakan_ekosistem_eksploitasi', 'label' => 'Jumlah kasus kerusakan ekosistem akibat eksploitasi hasil alam'],
                        ['code' => 'jumlah_kasus_kerusakan_ekosistem_bencana_alam', 'label' => 'Jumlah kasus kerusakan ekosistem akibat bencana alam'],
                        ['code' => 'jumlah_luas_pengikisan_tanah_abrasi', 'label' => 'Jumlah luas pengikisan tanah / abrasi'],
                        ['code' => 'jumlah_luas_alih_fungsi_lahan', 'label' => 'Jumlah luas alih fungsi pemanfaatan lahan'],
                        ['code' => 'jumlah_luas_area_restorasi_kerusakan_alam', 'label' => 'Jumlah luas area restorasi kerusakan alam'],
                        ['code' => 'jumlah_kerusakan_fasilitas_bangunan', 'label' => 'Jumlah kerusakan fasilitas bangunan'],
                    ],
                ],
                [
                    'code' => 'VI',
                    'label' => 'Pilot Project Keluarga Sehat Tanggap dan Tangguh Bencana Peduli Lingkungan',
                    'indicators' => [
                        ['code' => 'jumlah_keluarga_memiliki_bak_sampah', 'label' => 'Jumlah Keluarga yang memiliki bak sampah'],
                        ['code' => 'jumlah_anggota_bank_sampah', 'label' => 'Jumlah Anggota Bank Sampah'],
                        ['code' => 'jumlah_keluarga_memiliki_spal', 'label' => 'Jumlah keluarga yang menggunakan Sistem Pembuangan Air Limbah (SPAL)'],
                        ['code' => 'jumlah_kasus_banjir', 'label' => 'Jumlah kasus banjir'],
                        ['code' => 'jumlah_bak_sampah_milik_desa', 'label' => 'Jumlah bak sampah milik desa'],
                        ['code' => 'jumlah_rumah_ventilasi_udara_baik', 'label' => 'Jumlah Rumah dengan ventilasi udara yang baik'],
                        ['code' => 'jumlah_kasus_klb', 'label' => 'Jumlah kasus Kejadian Luar Biasa (KLB)'],
                    ],
                ],
                [
                    'code' => 'VII',
                    'label' => 'Pilot Project Keluarga Sehat Tanggap dan Tangguh Bencana Menuju Keluarga Sehat Berkualitas',
                    'indicators' => [
                        ['code' => 'jumlah_keluarga_dengan_2_anak', 'label' => 'Jumlah Keluarga dengan 2 anak'],
                        ['code' => 'jumlah_penduduk_berobat_ke_faskes', 'label' => 'Jumlah Penduduk yang berobat ke fasilitas kesehatan berdasarkan data di fasilitas kesehatan'],
                        ['code' => 'jumlah_kasus_penyakit_menular', 'label' => 'Jumlah kasus penyakit menular'],
                        ['code' => 'jumlah_kasus_penyakit_tidak_menular', 'label' => 'Jumlah kasus penyakit tidak menular'],
                        ['code' => 'jumlah_bayi_lahir_sehat', 'label' => 'Jumlah Bayi Lahir Sehat'],
                        ['code' => 'jumlah_bayi_lahir_cukup_bulan', 'label' => 'Jumlah Bayi Lahir Cukup Bulan'],
                        ['code' => 'jumlah_keluarga_anggota_gangguan_jiwa', 'label' => 'Jumlah keluarga yang memiliki anggota dengan kriteria penyakit gangguan jiwa'],
                    ],
                ],
                [
                    'code' => 'VIII',
                    'label' => 'Pilot Project Keluarga Sehat Tanggap dan Tangguh Bencana Menuju Keuangan Sehat',
                    'indicators' => [
                        ['code' => 'jumlah_keluarga_memiliki_asuransi_kesehatan', 'label' => 'Jumlah Keluarga yang memiliki Asuransi Kesehatan'],
                        ['code' => 'jumlah_kepala_keluarga_pengangguran', 'label' => 'Jumlah kepala keluarga yang tidak memiliki pekerjaan / Pengangguran'],
                        ['code' => 'jumlah_kepala_keluarga_tidak_memiliki_pekerjaan_tetap', 'label' => 'Jumlah kepala keluarga yang tidak memiliki pekerjaan tetap'],
                        ['code' => 'jumlah_kepala_keluarga_memiliki_penghasilan_tetap', 'label' => 'Jumlah Kepala Keluarga yang memiliki penghasilan tetap'],
                        ['code' => 'jumlah_ibu_hamil_memiliki_tabulin', 'label' => 'Jumlah Ibu hamil yang mempunyai tabungan bersalin (TABULIN)'],
                        ['code' => 'jumlah_keluarga_memiliki_tabungan', 'label' => 'Jumlah keluarga yang memiliki tabungan'],
                        ['code' => 'jumlah_keluarga_memiliki_aset_investasi', 'label' => 'Jumlah keluarga yang mempunyai aset untuk investasi'],
                    ],
                ],
                [
                    'code' => 'IX',
                    'label' => 'Pilot Project Keluarga Sehat Tanggap dan Tangguh Bencana Mewujudkan Keluarga Sehat Pasangan Usia Subur (PUS)',
                    'indicators' => [
                        ['code' => 'jumlah_ibu_melahirkan_bayi_sehat', 'label' => 'Jumlah Ibu melahirkan Bayi sehat'],
                        ['code' => 'jumlah_peserta_kb_wanita', 'label' => 'Jumlah peserta KB pada wanita'],
                        ['code' => 'jumlah_peserta_kb_pria', 'label' => 'Jumlah peserta KB pada pria'],
                        ['code' => 'jumlah_pus_masalah_kesehatan_reproduksi', 'label' => 'Jumlah Pasangan Usia Subur (PUS) yang memiliki masalah kesehatan reproduksi'],
                        ['code' => 'jumlah_pus_menikah_dibawah_usia_20_tahun', 'label' => 'Jumlah Pasangan Usia Subur (PUS) yang menikah dibawah usia <20 Tahun'],
                        ['code' => 'jumlah_wus_kehamilan_berisiko', 'label' => 'Jumlah Wanita Usia Subur dengan kehamilan beresiko'],
                        ['code' => 'jumlah_penderita_ims_pus', 'label' => 'Jumlah penderita penyakit infeksi menular seksual pada Pasangan Usia Subur (PUS)'],
                    ],
                ],
            ],
        ],
    ],
];
